version: '3.7'

services:
  ps_rsocket_client:
    build:
      context: ./rsocket-crud-client
      dockerfile: Dockerfile
      args:
        JAR_FILE: build/libs/*.jar

    image: psawesome/rsocket-client
    container_name: rsocket-client
    hostname: localhost
    ports:
      - "8090:8090"

    networks:
      - ps_rsocket_posts

networks:
  ps_rsocket_posts:
    driver: bridge
    internal: true
    external: true