version: '3.7'

services:
  ps_rsocket_server:
    build:
      context: .
      dockerfile: Dockerfile

      args:
        JAR_FILE: build/libs/*.jar
    container_name: ps_rsocket_server
    hostname: ps_rsocket_server
    image: psawesome/rsocket-server
    ports:
      - "7000:7000"
    networks:
      - ps_rsocket_posts


  ps_rsocket_client:
    build:
      context: ./rsocket-crud-client
      dockerfile: Dockerfile
      args:
        JAR_FILE: build/libs/*.jar

    image: psawesome/rsocket-client
    container_name: rsocket-client
    hostname: rsocket-client
    ports:
      - "8080:8080"

    depends_on:
      - ps_rsocket_server

    networks:
      - ps_rsocket_posts

networks:
  ps_rsocket_posts:
    driver: bridge
    internal: true
    external: true